config/routes.rb
Rails.application.routes.draw do

  resources :qnas do
		resources :qna_comments, only: [:create, :destroy]
	end
	
	resources :cafes
	
  # devise_for :users
  root 'home#index'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qna.rb
class Qna < ApplicationRecord
	resourcify
	include Authority::Abilities
	# @qna.updatable_by? @qna.deletable_by?
  belongs_to :user
	has_many :qna_comments, dependent: :destroy
end

app/models/qna_comment.rb
class QnaComment < ApplicationRecord
	resourcify
	include Authority::Abilities
	# @qna.updatable_by? @qna.deletable_by?
  belongs_to :user
  belongs_to :qna
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
	include  Authority::UserAbilities
	# current_user.can_update? / current_user.can_delete? 사용 가능
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :confirmable
	
	has_many :qnas, dependent: :destroy
	has_many :qna_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :isMale, :phone])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname, :isMale, :phone])
	end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/qna_comments_controller.rb
class QnaCommentsController < ApplicationController
	def create
		comment = QnaComment.new
		comment.user_id = current_user.id
		comment.content = params[:content]
		comment.qna_id = params[:qna_id]
		comment.save!
		redirect_to "/qnas/#{comment.qna_id}"
	end
	
	def destroy
		comment = QnaComment.find(params[:id])
		comment.delete
		redirect_to "/qnas/#{params[:qna_id]}"
	end
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
	before_action :authenticate_user!, only: [:new, :destroy, :update, :edit, :show]
	# before_action :check_ownership, only: [:create, :destroy, :update]
	
  def index
		@qna = Qna.all
  end

  def new
  end
	
	def create
		@qna = Qna.new
		@qna.user_id = current_user.id
		@qna.title = params[:title]
		@qna.content = params[:content]
		@qna.view_count = 0
		@qna.save
		redirect_to "/qnas/#{@qna.id}", notice: "질문 작성 완료"
	end
	
	def show
		@qna = Qna.find(params[:id])
		@comments = @qna.qna_comments.all
	end
	
  def edit
		authorize_action_for @qna
		@qna = Qna.find(params[:id])
  end
	
	def update
		authorize_action_for @qna
		@qna = Qna.find(params[:id])
		@qna.title = params[:title]
		@qna.content = params[:content]
		@qna.save
		redirect_to "/qnas/#{@qna.id}", notice: "수정 완료"
	end
	
	def destroy
		authorize_action_for @qna
		@qna = Qna.find(params[:id])
		@qna.delete
		redirect_to "/qnas", notice: "삭제 완료"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/qna_comments_helper.rb
module QnaCommentsHelper
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/views/cafes/index.html.erb
<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<h1>Cafes in Sinchon</h1>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

app/views/cafes/show.html.erb
<h1>Cafes#show</h1>
<p>Find me in app/views/cafes/show.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to myHome</h1>

<h2>Where do you wanna go?</h2>
<ul>
	<li>
		<button id="qna" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
		Q&A</button>
		<button id="cafe" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
		Cafe</button>
	</li>
</ul>

<img src='/background_cat.gif'></img>


<script>
	// Function to change the content of t2
	function goQna() {
		window.location.href = "/qnas";
	}

	function goCafe() {
		window.location.href = "/cafes";
	}
	// add event listener to table
	var el = document.getElementById("qna");
	el.addEventListener("click", goQna, false);
	
	var e2 = document.getElementById("cafe");
	e2.addEventListener("click", goCafe, false);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DohaeServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		<!-- 매터리얼 -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css">
		<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
		
		<!-- 구글맵 -->
		<script src="//maps.google.com/maps/api/js?key=[your API key]"></script>
		<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
		<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  </head>

  <body>
	
		<!-- Always shows a header, even in smaller screens. -->
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
			<header class="mdl-layout__header">
				<div class="mdl-layout__header-row">
					<!-- Title -->
					<a class="mdl-navigation__link" href="/">HOME</a>
					<a class="mdl-navigation__link" href="/qnas">Q&A</a>
					<!-- Add spacer, to align navigation to the right -->
					<div class="mdl-layout-spacer"></div>
					<!-- Navigation. We hide it in small screens. -->
					<nav class="mdl-navigation mdl-layout--large-screen-only">
						<% if user_signed_in?%>
							<p class="mdl-navigation__link"><%= current_user.nickname%></p>
						<% end%>
					</nav>
					<!-- Right aligned menu below button -->
					<button id="demo-menu-lower-right"
									class="mdl-button mdl-js-button mdl-button--icon">
						<i class="material-icons">more_vert</i>
					</button>
					<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
							for="demo-menu-lower-right">
						<% if !user_signed_in?%>
							<li class="mdl-menu__item"><a href="/users/sign_in">로그인</a> </li>
							<li class="mdl-menu__item"><a href="/users/sign_up">회원가입</a></li>
						<% else%>
							<li class="mdl-menu__item"><a href="/users/sign_out" data-method = 'delete'>로그아웃</a></li>
							<li class="mdl-menu__item"><a href="/users/edit">회원정보 수정</a></li>
						<% end%>
					</ul>
				</div>
			</header>
	
			<main class="mdl-layout__content">
				<div class="page-content"><!-- Your content goes here -->				
					
					<p class="notice"><%= notice %></p>
					<p class="alert"><%= alert %></p>
					<%= yield %>
					
					<!-- mega footer -->
					<footer class="mdl-mega-footer">
						<div class="mdl-mega-footer__middle-section">

							<div class="mdl-mega-footer__drop-down-section">
								<input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
								<h1 class="mdl-mega-footer__heading">Features</h1>
								<ul class="mdl-mega-footer__link-list">
									<li><a href="#">About</a></li>
									<li><a href="#">Terms</a></li>
									<li><a href="#">Partners</a></li>
									<li><a href="#">Updates</a></li>
								</ul>
							</div>

							<div class="mdl-mega-footer__drop-down-section">
								<input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
								<h1 class="mdl-mega-footer__heading">Details</h1>
								<ul class="mdl-mega-footer__link-list">
									<li><a href="#">Specs</a></li>
									<li><a href="#">Tools</a></li>
									<li><a href="#">Resources</a></li>
								</ul>
							</div>

							<div class="mdl-mega-footer__drop-down-section">
								<input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
								<h1 class="mdl-mega-footer__heading">Technology</h1>
								<ul class="mdl-mega-footer__link-list">
									<li><a href="#">How it works</a></li>
									<li><a href="#">Patterns</a></li>
									<li><a href="#">Usage</a></li>
									<li><a href="#">Products</a></li>
									<li><a href="#">Contracts</a></li>
								</ul>
							</div>

							<div class="mdl-mega-footer__drop-down-section">
								<input class="mdl-mega-footer__heading-checkbox" type="checkbox" checked>
								<h1 class="mdl-mega-footer__heading">FAQ</h1>
								<ul class="mdl-mega-footer__link-list">
									<li><a href="#">Questions</a></li>
									<li><a href="#">Answers</a></li>
									<li><a href="#">Contact us</a></li>
								</ul>
							</div>

						</div>

						<div class="mdl-mega-footer__bottom-section">
							<div class="mdl-logo">Title</div>
							<ul class="mdl-mega-footer__link-list">
								<li><a href="#">Help</a></li>
								<li><a href="#">Privacy & Terms</a></li>
							</ul>
						</div>

					</footer>
				</div>
			</main>
		</div>
		
  </body>
</html>

app/views/qnas/edit.html.erb
<% if current_user != @qna.user %>
	<p>권한이 없습니다.</p>
	<a href = '/'>되돌아가기</a>
<%else%>

<h1>질문 수정하기</h1>
<%= form_tag qna_path, method: :PATCH, multipart: true do %>
	제목 : <input type="text" name="title" value=<%=@qna.title%>><br>
	내용 : <%=text_area_tag :content, @qna.content %><br>
	<%= button_tag "수정하기", :data => {:confirm => "수정하시겠습니까?"} %>
<% end %>



<%end%>

app/views/qnas/index.html.erb
<h1>QnA</h1>
<h2>Ask Me Anything</h2>
<strong><a href='/qnas/new'>질문하기</a></strong>

<table style="width:100%">
  <tr>
    <th style="width:30%">작성자</th>
    <th>제목</th> 
  </tr>
	<% @qna.each do |x| %>
	  <tr  align="center">
			<td style="width:30%"><%=x.user.email%></td>
			<td><a href='/qnas/<%=x.id%>'><%=x.title%></a></td> 
		</tr>
	<%end%>
</table>

app/views/qnas/new.html.erb
<h1>질문하기</h1>
<p>아래 칸을 작성해주세요.</p>

<%= form_tag qnas_path, multipart: true do %>
	제목 : <input type="text" name="title"><br>
	내용 : <%=text_area_tag :content, nil, placeholder: "무엇이 궁금한가요?" %><br>
	<%= button_tag "작성하기", :data => {:confirm => "글을 올리시겠습니까?"} %>
<% end %>

app/views/qnas/show.html.erb
<h1><%=@qna.title%></h1>
<p>글쓴이 : <%=@qna.user.email%></p>
<b>내용</b>
<p><%=@qna.content%></p>
<a href='/qnas'>목록 </a>
<% if current_user == @qna.user%>
	<a href='/qnas/<%=@qna.id%>/edit'>수정 </a>
	<a href='/qnas/<%=@qna.id%>' data-confirm = '삭제하시겠습니까?' data-method = 'delete'>삭제 </a>
<% end%>

<p>댓글 입력하기</p>
<form action="/qnas/<%=@qna.id%>/qna_comments" method="POST">
	<input type='hidden' name='authenticity_token' value=<%=form_authenticity_token%>></input>
	내용 : <input type="text" name="content" placeholder="댓글 입력하기"></input>
	<input type="submit" value="작성하기"></input>
</form>

<% if true%>
	<table style="width:1000px">
		<tr>
			<th style="width:30%">작성자</th>
			<th>내용</th> 
		</tr>
		<% @comments.each do |x| %>
			<tr>
				<td style="width:30%"><%=x.user.email%></td>
				<td><%=x.content%>&emsp;
				<% if current_user == x.user %>
					<a href = '/qnas/<%=@qna.id%>/qna_comments/<%=x.id%>' data-confirm = '댓글을 삭제하시겠습니까?' data-method = 'delete'>삭제</a>
				<%end%></td>
			</tr>
		<%end%>
	</table>
<%end%>